### ISSUE TITLE
Antenna

### ISSUE THREAD

**Issue by zimler** [osqzss/bladeGPS#10]
I have a crude antenna built, but I believe the signal is pretty messy. Any suggestions on a proper antenna to buy?

**Comment by osqzss** [comment]
The TX power of the bladeRF is too strong, and it will simply jam the receiver. You need proper attenuation to make it work. Try 30dB to 50dB attenuation and see how it goes.

**Comment by zimler** [comment]
To confirm: You are suggesting this even for a non-direct connection?

**Comment by osqzss** [comment]
First of all, the GPS radio signal transmission would be illegal. Please check the local regulations of the place that you reside.

The GPS signal reception power on the ground is around -130dBm to -110dBm. I don't know the exact TX power of the bladeRF at the GPS frequency, but the typical value is said about +6dBm. You could easily mess up the GPS receivers of your neighborhoods.

**Comment by zimler** [comment]
This is, of course, proper RF lab test environments. Not a residential setting.
