### ISSUE TITLE
Pause dynamic path

### ISSUE THREAD

**Issue by zimler** [osqzss/bladeGPS#11]
I have tried the interactive mode and that works well. Seems to loop the same location unless you move using the keyboard. If I were to use a dynamic mode file, would it be simple to add a pause function that would loop cause the application to pause the file and loop my current location?

I'm still learning about the bladerf, so I apologize for the potential newbie question. :-)

**Comment by osqzss** [comment]
Actually, path generation is not a trivial job even for a simple pause motion. You have to take the user dynamics into consideration. You cannot simply "stop" there when you are driving at 100km/h. I would rather leave that work to the motion file generator of the user.

**Comment by zimler** [comment]
As I continue to read through this code, that will probably make sense. Thanks for taking time to respond.
