### ISSUE TITLE
Rinex file reload

### ISSUE THREAD

**Issue by zimler** [osqzss/bladeGPS#12]
I assume that the rinex file is loaded only once when the command starts the application. If I were updating the rinex file with a newer file version, but kept the same name while the application is running, triggering a reload of the file, could that be a simpler way to generate closer to real-time date/time information?

**Comment by osqzss** [comment]
It is possible, but you need an additional thread to read the RINEX file while the simulator is running.

**Comment by zimler** [comment]
Thank you for taking the time to respond :-)
