### ISSUE TITLE
Changing the date in the BRDC file

### ISSUE THREAD

**Issue by nzkarit** [osqzss/bladeGPS#14]
Hi,

I am working with v0.1 of bladeGPS rather than v0.2 because of #13.

I have edited the brdc (it was originally from 2016-05-31) to have today's date in it (2016-07-26). I am running with the following command line:

```
./bladegps -e dave.16n -l 30.286502,120.032669,100 -t 2016/07/26,01:00:00
```

I would expect the GPS date to be 2016-07-26.

But instead I am receiving 2016-05-31 as the date when viewed in cgps (part of the GPSd library). Though the time aspect matches the command line.

Please see the following screenshot:
- On the left is the brdc file. 
- Top right is the bladegps script running. 
- The bottom right is the output of cgps

![bladegps-date-wrong-time-correct](https://cloud.githubusercontent.com/assets/6285569/17118202/bd4da2e0-5313-11e6-8ecb-aafe23e3cc32.png)

**Comment by osqzss** [comment]
RINEX file editing is not something supported by the bladeGPS. If you want to do it by yourself, you have to change the corresponding TOE (time of ephemeris) and the GPS week number in addition to the TOC (time of clock). The location of the TOE is the first column of the fourth row, and the GPS week number is found in the third column of the sixth row.
https://igscb.jpl.nasa.gov/igscb/data/format/rinex210.txt

**Comment by zimler** [comment]
@nzkarit did you try editing like @osqzss suggested? Curious if you had success.

Just found this, I haven't tried it yet. Looks promising. https://github.com/SGL-UT/GPSTk/blob/133e24f5747120f57f44624d7a220814b495f27a/ext/apps/Rinextools/README

**Comment by osqzss** [comment]
Try the latest gps-sdr-sim with '-T' option to overwrite the TOC and TOE to the user-specified scenario start time. If it works okay, I will merge it to bladeGPS.

**Comment by zimler** [comment]
@osqzss the -T option in gps-sdr-sim performed as expected. I would merge it to this project.

**Comment by osqzss** [comment]
I'm also working on the leap-seconds support now. The both will be merged to bladeGPS in this week.

**Comment by zimler** [comment]
Would it be easy to have an option that would use current date and time? Like -T NOW or a separate option like -TC

**Comment by osqzss** [comment]
"-T now" seems nice. I will add this option, too.

**Comment by zimler** [comment]
Thank you! That's going to be very helpful.

**Comment by zimler** [comment]
@osqzss  If the date and time I choose is in local date and time, is there any conversion of the date/time to UTC or is it used as-is? If there is a conversion, then I would want to do an additional test.

**Comment by osqzss** [comment]
Try `mktime` and `gmtime`.
http://stackoverflow.com/questions/1764710/converting-string-containing-localtime-into-utc-in-c

**Comment by osqzss** [comment]
"-T now" option is available in gps-sdr-sim.

**Comment by osqzss** [comment]
"-T" option is now available in bladeGPS

**Comment by zimler** [comment]
Excellent, thank you.

**Comment by nzkarit** [comment]
Thanks working for me on gps-sdr-sim. Haven't tried on the bladeGPS as still trying to figure out libraries on linux.
