### ISSUE TITLE
Why max duration of 86400?

### ISSUE THREAD

**Issue by sinak** [osqzss/bladeGPS#16]
Hi @osqzss - thanks so much for building this! With a few small tweaks it seems to work great on Ubuntu 16.04.

A quick question for you: Is there a particular reason for the 86400 second (24 hour) limit? Would there be any problems with running this without a time limit?

**Comment by osqzss** [comment]
The simulated navigation message is generated by the combined broadcast navigation message (brdc) file. It is released by IGS data centers on a daily basis.
