### ISSUE TITLE
Failed to set TX frequency

### ISSUE THREAD

**Issue by gasparjoao** [osqzss/bladeGPS#17]
Hello

I'm trying to use this simulator in real time with bladeRF but I'm having some problems ..
I've done the "Building libbladeRF for Windows" step by step and I managed to do so.
Now I've done the "Build on Windows with Visual Studio" of the bladeGPS simulator step by step and I also managed to do it, but now I run the executable and I get the error "Failed to set TX frequency: Invalid operation or parameter".
Can you explain what the problem might be?

**Comment by osqzss** [comment]
Try this pre-built executable: https://github.com/osqzss/bladeGPS/releases

**Comment by gasparjoao** [comment]
It gives me the same error "Failed to set TX frequency: Invalid operation or parameter"

**Comment by gasparjoao** [comment]
![image](https://user-images.githubusercontent.com/11621610/40178758-52cbb40a-59da-11e8-8e03-d07e8f0edbba.png)

**Comment by gasparjoao** [comment]
not the same error now is "An unexpected error occured"

**Comment by osqzss** [comment]
Would you try to install the latest library with the windows installer and update the bladeRF firmware?
https://nuand.com/bladeRF-doc/guides/bladeRF_windows_installer.html

**Comment by gasparjoao** [comment]
i got it running yeahh.
Using -g nmea.txt file its really real-time transmition?
It seems like it takes a lot of time to get location (ex smartphone).

**Comment by osqzss** [comment]
May I ask the cause of the error for our reference?
