### ISSUE TITLE
Almanac Week Rollover

### ISSUE THREAD

**Issue by Meown12** [osqzss/bladeGPS#19]
Hi,

I was trying to use the almanac option to hopefully get better simulation results for future dates, in the limits of the almanac of course, but I received an error with the almanac file from [here](https://celestrak.com/GPS/almanac/Yuma/2019/almanac.yuma.week0004.319488.txt) and the rinex from [here](ftp://cddis.nasa.gov/gnss/data/daily/2019/brdc/brdc1260.19n.Z). When reading through the internet I found out that this may be related to the week rollover that happened last weekend.
The error I get is:
ERROR: Invalid time of almanac.
1028
2052
Abort.
(Where the two numbers are something I added in to find out what time it reads - first number: time of the almanac (gps week number); second number: time of ephemeris file (gps week number))

Would this issue be solved by adding another 1024 to the coefficient in gpssim.c line 1041 ? Or would it be worth putting this into a constant for easier finding?

Thanks 

Max

**Comment by osqzss** [comment]
You're right. Please add another 1024 to the GPS week number in the almanac file.
